before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libdbus-1-dev
language: rust
rust:
  - stable
  - nightly

matrix:
    include:
        - os: osx
        - os: linux


script:
  - cargo build --verbose


