language: rust

matrix:
    include:
        - os: osx

        - os: linux
          before_install:
            - sudo apt-get update -qq
            - sudo apt-get install -y libdbus-1-dev

script:
  - cargo build --verbose


